import requests
import csv
import os
import time
import random
from urllib.parse import urlparse
from dotenv import load_dotenv

# Laedt die Variablen aus der .env-Datei im Projektordner
load_dotenv()

# ============================================================
# KONFIGURATION
# ============================================================

# API-Key kommt aus der .env-Datei 
API_KEY = os.getenv("AHREFS_API_KEY")

if not API_KEY:
    raise SystemExit(
        "Kein API-Key gefunden.\n"
        "Lege in der .env-Datei die Zeile 'AHREFS_API_KEY=dein_key' an\n"
        "und achte darauf, dass die .env im selben Ordner wie das Skript liegt."
    )

API_URL = "https://api.ahrefs.com/v3/public/domain-rating-free"
CSV_DATEI = "ergebnisse_domain_authority_ahrefs.csv"

# Da das Domain Rating pro DOMAIN gilt (nicht pro URL), lohnt es sich,
# jede Domain nur einmal abzufragen. Das Ergebnis wird gecacht und
# trotzdem für jede Ursprungs-URL in die CSV geschrieben.
NUR_EINE_ABFRAGE_PRO_DOMAIN = True

# Trage hier deine URL-Liste ein
urls = [
   "https://www.federnwerk.com/federn/drahtbiegeteile/",
    "https://www.fernholz.biz/",
    "https://www.fiabuc.de/produkte/kabelb%C3%A4ume",
    "https://www.foodtrading.de/industrie/",
    "https://www.forfarmersteamagrar.de/",
    "https://www.frapak.com/de/",
    "https://www.freiberger-druckguss.de/",
    "https://www.fries-kt.com/produkte/verpackung/ratgeber-industrieverpackungen/ratgeber-lebensmittelkonformitaet/",
    "https://www.frischdienst-union.de/",
    "https://www.fuessmann-federn.de/",
    "https://www.fuessmann-federn.de/unternehmen",
    "https://www.greiner-gpi.com/de/Greiner-Packaging/Kunststoffverpackungen",
    "https://www.gropack.de/",
    "https://www.gs-genossenschaft.de/agri",
    "https://www.gs-genossenschaft.de/digitale-services/zertifikate",
    "https://www.gwp-ag.de/",
    "https://www.haertecenter.de/",
    "https://www.handtmann.de/fileadmin/user_upload/Geschaeftsbereiche/Leichtmetallguss/Ueber_Uns/Zertifikate_Englisch/IATF-16949-MGW-EN-2024.pdf",
    "https://www.handtmann.de/leichtmetallguss/rechtliches/impressum",
    "https://www.hannes-federn.de/files/KATALOG.pdf?ts=1740575556",
    "https://www.heismann.de/branchenloesungen/innovative-automotive-technik",
    "https://www.henselundpartner.de/drahtbiegeteile-schenkelfedern.php",
    "https://www.heuschkel-druckguss.de/",
    "https://www.hilmer-cnc-technik.de/",
    "https://www.hirschvogel.com/en/",
    "https://www.hl-futter.de/de/qualitaet/zertifikate",
    "https://www.inometa.de/lohnbeschichtung/",
    "https://www.ipek-industries.com/aluminiumdruckguss/",
    "https://www.jokey.com/",
    "https://www.jokey.com//",
    "https://www.jokey.com/produkte",
    "https://www.juetro-tkk.de/produktuebersicht/",
    "https://www.juj-beschichtung.de/",
    "https://www.kabelbaumfertigung.de/",
    "https://www.kohlhage.de/",
    "https://www.ksmcastings.com/",
    "https://www.ktl-mhk.de/ktl/",
    "https://www.kufatec.de/de/services/cable-manufacture.html",
    "https://www.kummer-gmbh.de/home.html",
    "https://www.lackierzentrum-limbach.de/",
    "https://www.landhandel-grossmann.de/",
    "https://www.leyh.de/service/liefergebiet.php",
    "https://www.luxotronic.de/",
    "https://www.middeke-lack.de/leistungen/industrielackierungen",
    "https://www.milkabelsystems.com/kabellieferant-deutschland/",
    "https://www.muetron.de/kabelbaeume/",
    "https://www.nestleprofessional.de/",
    "https://www.oberplast.de/content/1_home.htm",
    "https://www.oltrop-zerspanungstechnik.de/",
    "https://www.onshii.de/",
    "https://www.pecnolet.de/",
    "https://www.polymersynthese.com/home/faqs/lebensmittelecht",
    "https://www.pw-sachsenlack.de/index.php?menuid=34",
    "https://www.pw-sachsenlack.de/willkommen",
    "https://www.raiffeisen-vital.de/mischfutter/qualitaet/",
    "https://www.rebel.de/",
    "https://www.rhoese-frischdienst.de/",
    "https://www.ritzi-lackiertechnik.de/serienfertigung/",
    "https://www.saatenberg.com/produkte/oele",
    "https://www.stalter-federn.de/material.html",
    "https://www.subtil-group.com/de/produkte/drahtformteile.html",
    "https://www.suedplast.de/",
    "https://www.sunrise-casta.com/",
    "https://www.szae.de/de/content/900/A43E_EV-0393_Allgemeine_Einkaufsbedingungen_SZAE_Rev._01.pdf",
    "https://www.szae.de/en/stamping_parts-312.html",
    "https://www.thg-norderstedt.com/de/",
    "https://www.trockenwerk-eldena.de/mischfutter/",
    "https://www.uniqfood.de/de/verantwortung/",
    "https://www.univ-pulverbeschichtung.de/",
    "https://www.varioplast.de/de/technologien-prozesse/oberflaechenveredelung-deutschland-pvd-lackierung-laser",
    "https://www.vdf-springs.com/de/impressum.php",
    "https://www.vortella.de/unternehmen/",
    "https://www.walter-rau.de/fuer-profis/foodservice/unser-sortiment",
    "https://www.winklerundschorn.de/",
    "https://www.wr-maschinenbau.de/",
    "https://www.wuebken.de/",
    "https://www.zf.com/products/de/cars/home/cars.html",
    "https://www.zismann.de/",
    "https://ae-group.de/de/news-ae-group/newsreader/ae-group-wechselt-von-der-eigenverwaltung-in-regelinsolvenzverfahren",
    "https://ae-group.de/files/downloads/Zertifikate/IATF16949_allg_2024_de.pdf",
    "https://aftermarket.zf.com/de/aftermarket-portal/unser-portfolio/pkw-transporter/produkte/antriebsstrang/",
    "https://aftermarket.zf.com/de/aftermarket-portal/unsere-marken/lemfoerder/",
    "https://agh-weikmann.de/wissenswertes",
    "https://agravisprod-media.e-spirit.cloud/9b22dc98-182f-4a49-a2fa-24e024a2e40b/content/unsere-leistungen/tiere/zertifikate-09-24/gmp-futtermittelsicherheit/agravis-kraftfutterwerk-oldenburg-gmbh_kw-oldenburg_deutsch.pdf",
    "https://agravisprod-media.e-spirit.cloud/9b22dc98-182f-4a49-a2fa-24e024a2e40b/content/unsere-leistungen/tiere/zertifikate-09-24/gmp-futtermittelsicherheit/agravis-mischfutter-ostwestfalenlippe-gmbh_kw-minden_englisch.pdf",
    "https://aluminium-giesserei.de/",
    "https://ansorge.com/",
    "https://appinger-ks.de/",
    "https://aptar.com/en-us/",
    "https://aptar.com/en-us/news-events/aptar-closures-freyung-germany-plant-receives-iscc-plus-certification",
    "https://ast-kanister.de/de/",
    "https://b-k-kabeltechnik.de/kabelkonfektion/",
    "https://b2b.prepmymeal.de/",
    "https://b2b.prepmymeal.de/en/pages/mitarbeiterverpflegung",
    "https://bard1856.de/wp-content/uploads/2025/08/2025_ZERTIFIKAT_IFS-F_AGZ2314_nach-Erweiterungsaudit.pdf",
    "https://bat-agrar.de/sparten/tiernahrung/",
    "https://bat-agrar.de/wp-content/uploads/sites/34/2025/07/qs-zertifikat-bat-agrar-muessen.pdf",
    "https://bergland-food.de/",
    "https://bestcon-food.de/unternehmen/",
    "https://beweka.com/",
    "https://bia-group.com/unternehmen/",
    "https://bkt.de/produkte/kanister-kannen-flaschen/",
    "https://bkt.de/unternehmen/",
    "https://brand-group.com/brandgroup/zahlen-fakten/",
    "https://brand-group.com/en/",
    "https://brand-group.com/en/products/based-on-springs/wire-forming-parts/",
    "https://brand-group.com/produkte/nach-federn/drahtbiegeteile-/-drehstabfeder/",
    "https://brand-group.com/standorte-partnerschaften/",
    "https://brenne.de/produkte/",
    "https://broekelmann-shop.de/",
    "https://broering.com/ueber-uns/standorte/",
    "https://careers.motherson.com/de/location/barchfeld",
    "https://castconcept.de/files/cast-concept-Produktspektrum.pdf",
    "https://catalog.paccor.com/",
    "https://cdn.dieseltechnic.com/pdf/Certificates/ISO_45001_2018/DOC_0502_EN_-_Certificate_45001_2018_Rev._4.2_2021-04.pdf",
    "https://cis.de/anwendungsbereiche/automotive/",
    "https://cook-chill-gmbh.de/",
    "https://copack.eu/downloads/9/IFS-RTK-equiry%2006.2019.pdf",
    "https://cotarko.de/unternehmen/",
    "https://de-pack.de/b2b-verpackungen",
    "https://deikra-futter.de/startseite.html",
    "https://die-maler-gmbh.de/lackierarbeiten/",
    "https://drahtbiegeteile.de/",
    "https://edeka-foodservice-gruppe.de/",
    "https://edeka-foodservice.de/",
    "https://edeka-foodservice.de/edeka-foodservice-in-meiner-naehe/wiesbaden",
    "https://edeka-foodservice.de/markenpartner/salomon-foodworld",
    "https://eisenmann-druckguss.de/downloads/pdf/16949_2024.pdf",
    "https://eisenmann-druckguss.de/ueber-eisenmann/",
    "https://eisenmann-druckguss.de/ueber-eisenmann/index.php",
    "https://elke-plastic.de/",
    "https://elringklinger.de/en/products-technologies",
    "https://em-kunststofftechnik.de/fileadmin/user_upload/IATF_16949__EMK_Monastir_01_111_1800771_Main_EN_2025.pdf",
    "https://em-kunststofftechnik.de/kabelkonfektion/",
    "https://engelking.com/de-de/loesungen/wiring-cable-solutions",
    "https://erxleben.biz/about",
    "https://erxleben.biz/qualitaetswesen",
    "https://etimex.de/",
    "https://euro-food.de/home",
    "https://fesser-sondermaschinenbau.de/",
    "https://fixauto.com/altmuehlfranken/de/lohnbeschichtung",
    "https://fleros.de/en/blogs/news/lebensmittelecht-und-nachhaltig-kunststoffverpackungen-fischindustrie",
    "https://fluessigfutter.de/futtermittel/",
    "https://fondium.eu/ktl/",
    "https://foodservice.hilcona.com/de/",
    "https://foodservice.hilcona.com/de/65/Ueber-Uns.html",
    "https://fricke-feinmechanik.de/",
    "https://fritzschmidt-metallgiesserei.de/",
    "https://fuf-fisch.de/",
    "https://fuw.net/",
    "https://fuw.net/futtermittel/",
    "https://gerweck-gmbh.de/unternehmen",
    "https://graf-werdohl.de/",
    "https://grueber.de/unternehmen/",
    "https://gsmotion.de/produkte/oberflaechenbeschichtung/",
    "https://haeusler-frischeservice.de/cf-foodservice/",
    "https://harzguss.de/",
    "https://harzguss.de/fileadmin/user_upload/Service/Downloads/IATF_16949-247665-2017-AQ-GER-IATF-5-de-DE-20240227-20240227230801.pdf",
    "https://hdo-gmbh.com/wp-content/uploads/Zertifikat_iatf_16949_hdo-pb_de.pdf",
    "https://heichegroup.com/de/",
    "https://heichegroup.com/en/locations/details/heiche-saxony/",
    "https://heptec.de/maerkte-branchen/automotiv/",
    "https://heptec.de/qualitaet/",
    "https://heuchemer.de/",
    "https://hk-praezisionsteile.de/",
    "https://hofmann-oberflaeche.de/",
    "https://holzapfel-group.com/en/branchen-solutions/",
    "https://holzapfel-group.com/ihr-mehrwert/kompetenzzentrum/glossar-der-galvanotechnik/e/erstmuster-pruefbericht/",
    "https://holzapfel-group.com/index.php?L=4&id=135",
    "https://holzapfel-group.com/ueber-uns/",
    "https://hutzeltechnics.de/autoindustrie/",
    "https://ibex-lohnfertigung.de/",
    "https://ilb-gmbh.de/",
    "https://inter-oil.de/produkte/",
    "https://jobportal.sano.de/Softwarearchitekt-mwd-Smart-Farming-Datenanalyse-KI-mwd-de-j465.html",
    "https://jobs.aptar.com/job/Freyung-Duales-Studium-Kunststofftechnik-%28mwd%29-BY-94078/1365864333/",
    "https://kabelbaeume.de/english.html",
    "https://kabelbaumfertigung.de/",
    "https://kabelform.com/ueber-uns",
    "https://kabelkonfektion.com/",
    "https://karriere.brand-group.com/jobs/werkstudent-industrial-engineer-it-m-w-d-in-anroechte-bei-lippstadt/",
    "https://ke-elektronik.de/wp-content/uploads/2022/02/22-02-16-Leitfaden-zur-Lieferantenbewertung.pdf",
    "https://ketterer-druckguss.de/impressum/",
    "https://kirchhoff-automotive.com/de/",
    "https://kirchhoff-automotive.com/products-competencies/tools/parent-company/",
    "https://klinkmann-federn.de/",
    "https://kornkraft.com/",
    "https://kreher-lackier.de/",
    "https://kuwertz.de/",
    "https://lackierzentrum-reichenbach.de/industrielackierung/",
    "https://lamotte-oils.de/",
    "https://lamotte-oils.de/download/2179/?tmstv=1706877331",
    "https://lamotte-oils.de/wp-content/uploads/sites/2/dlm_uploads/2024/02/IFS-Broker.pdf",
    "https://lamotte-oils.de/wp-content/uploads/sites/2/dlm_uploads/2026/01/IFS-Food-HLO-Englisch-20.03.2027.pdf",
    "https://lamotte-oils.de/zertifizierungen/",
    "https://lange-ktl.de/",
    "https://laupp-gmbh.de/",
    "https://linhardt.com/",
    "https://linhardt.com/kontakt/",
    "https://linhardt.com/kunststofftuben/",
    "https://link-gmbh.de/company.html",
    "https://mega-tierernaehrung.com/unternehmen/",
    "https://metakem.de/produkte/sonderanfertigungen-in-der-edelmetallchemie-metakem/lohnbeschichtung-platin/",
    "https://muepraez.de/",
    "https://my.bat-agrar.de/fusion-atr-beiselen",
    "https://my.forfarmers.de/en/login",
    "https://natzan-packaging.com/",
    "https://neumann-verpackungen.de/",
    "https://nordische-oelwerke.de/",
    "https://nova-industriedienstleistungen.de/elektromechanische-baugruppen/",
    "https://nova-industriedienstleistungen.de/kabelbaum-konfektionierung/",
    "https://oberplast.de/",
    "https://oelmanufaktur-sankelmark.de/shop/",
    "https://olenex.com/about-us/",
    "https://online-shop.sander-gruppe.com/produkt-shy-sortiment/menue-shy-schalen/",
    "https://ottmarmayer.de/",
    "https://palbo-gmbh.de/",
    "https://palbo-gmbh.de/unternehmen/",
    "https://paul-oberflaechentechnik.de/firmenkunden/",
    "https://peotec.com/",
    "https://phiesel-gmbh.de/",
    "https://pieron.international/",
    "https://platenius-federn.de/draht-metallwaren/produkte/drahtbiegeteile.php",
    "https://poehner-hamburg.com/de/",
    "https://point-of-food.de/",
    "https://point-of-food.de/upload/pdf/dokument_1780040814_2_point_of_food_ifsfood_v8_2026en.pdf",
    "https://poly-pack.de/",
    "https://product-catalogue.alpla.com/es/product-catalogue?f%5B0%5D=category%3A1&f%5B1%5D=country%3AGermany&f%5B2%5D=country%3AItaly&f%5B3%5D=country%3APoland&f%5B4%5D=country%3ARomania&f%5B5%5D=country%3ASpain&f%5B6%5D=default_market_segments%3ABeauty+care&f%5B7%5D=default_market_segments%3AFood&f%5B8%5D=default_market_segments%3AHome+care&f%5B9%5D=shape%3ARound&page=0",
    "https://psw-umformtechnik.de/",
    "https://pt-dresden.de/de/grossserienfertigung",
    "https://pt-dresden.de/en/machined-parts",
    "https://rgenau-industries.de/",
    "https://rgenau-industries.de/ila-willkommen/",
    "https://rgenau-industries.de/oberflaechenbeschichtung/",
    "https://rgenau-industries.de/ueber-uns/historie/",
    "https://rmw.de/de/",
    "https://rmw.de/de/service/kabelkonfektionierung",
    "https://robert-schroeder.de/",
    "https://rtautomotive.de/",
    "https://rupf-industries.com/en/rupf-industries/about-us/locations-contacts/",
    "https://rupf-industries.com/en/rupf-industries/business-segments/automotive/rupf-atg-casting/",
    "https://sander-druckguss.de/unternehmen/",
    "https://sander-druckguss.de/wp-content/uploads/2023/08/161555-Sander-QM-WA-23-ay-EN.pdf",
    "https://sander-gourmet.com/downloads/Sander_Angebot_verpackte_Gerichte_2020_web.pdf",
    "https://sander-kanteenie.com/",
    "https://sano24.de/media/c4/1b/1a/1715594175/Pastus%2B.pdf",
    "https://sas-jena.com/de/leistungen/kabelkonfektion/",
    "https://saumweber.biz/",
    "https://saumweber.biz/service/zertifikate",
    "https://scheiba-gmbh.de/",
    "https://schmaleundschulte.de/",
    "https://schulze-druckguss.de/",
    "https://schumacher-federn.de/materialien-werkstoffe-und-oberflaechen/",
    "https://schumacher-federn.de/produkte/",
    "https://semtron.de/",
    "https://service.transgourmet.de/goodies/menuemanager/",
    "https://shop.chefsculinar.de/de-de",
    "https://shop.meyer-menue.de/",
    "https://spe-paul.de/leistungsuebersicht/automotive-fahrzeugbau/",
    "https://stanger-drehteile.de/leistungen/",
    "https://stremel.de/",
    "https://stueken.com/",
    "https://stueken.com/de/branchen/automotive",
    "https://stueken.com/stueken/Dokumente/Downloads/Broschueren/Stueken_Corporate_Information.pdf",
    "https://sumitomoelectric.com/company/office_group_companies/sumitomo-electric-bordnetze-se",
    "https://sustainability.jokey.com/ppwr/",
    "https://tooliss.de/en/",
    "https://tzoleipzig.de/",
    "https://tzoleipzig.de/lack-und-pulverbeschichtung/",
    "https://unger-kabelkonfektion.de/kontakt/",
    "https://vacutherm.de/",
    "https://vandemoortele.com/de-de/produkte/plant-based-food-solutions",
    "https://vdf-federn.de/",
    "https://vdf-springs.com/de/standorte.php",
    "https://vfi.co.at/de/",
    "https://viro.com/",
    "https://wagner-fahrzeugteile.de/",
    "https://wagner-fahrzeugteile.de/de-wAssets/docs/zertifikate/de/31622137-Wagner-GmbH-Co.-Fahrzeugteilefabrik-KG-CERTIFICATE-Deutsch-2025-08-13-IATF25.pdf",
    "https://weiss-automotive.de/",
    "https://wmt-online.de/",
    "https://wmt-online.de/praezisionsdrehteile",
    "https://wolf-coating.de/automotive/",
    "https://wp.breidert-galvanik.de/ueber-uns/",
    "https://wt-direct.de/pages/lohnfertigung",
    "https://wundg.de/ueber-uns/",
    "https://www.3f-gmbh.de/produkte/lohnfertigung/",
    "https://www.a-weber.com/company",
    "https://www.a-weber.de/fileadmin/user_upload/zertifikate/wst/261855_-_weber_weinstadt_gmbh_-_certificate_-_deutsch_-_2024-05-21_-_iatf16.pdf",
    "https://www.aalberts-st.com/de/branchen/automobilindustrie/",
    "https://www.aalberts-st.com/de/standorte/zwoenitz/",
    "https://www.aberger.de/de/branchenloesungen/",
    "https://www.aberger.de/files/downloads/001184_-_A._Berger_Praezisionsdrehteile_GmbH_Co._KG_-_CERTIFICATE_-_deutsch_-_2024-06-18_-_IATF25-1.pdf?t=1753352403",
    "https://www.accomplast.de/beschichtung.html",
    "https://www.acps-automotive.com/wp-content/uploads/_media/mediathek/download/IATF-16949-St-Egidien-en.pdf",
    "https://www.acs-innovations.de/fileadmin/user_upload/Unternehmen/Netzwerk-Traegerverein/Profile_Mitgliedsunternehmen/Sch%C3%B6tt-Druckgu%C3%9F_GmbH.pdf",
    "https://www.adm.com/en-us/news/news-releases/new-full-function-olenex-jv-provides-comprehensive-integrated-capabilities-in-edible-oils-and-fats/",
    "https://www.ae-group.de/de/news-ae-group/newsreader/ae-group-wechselt-von-der-eigenverwaltung-in-regelinsolvenzverfahren",
    "https://www.ae-group.de/files/downloads/Zertifikate/IATF16949-allg-2022-de.pdf",
    "https://www.ae-group.de/files/downloads/Zertifikate/IATF16949-allg-2024-de.pdf",
    "https://www.agravis.de/de/unternehmen/jobs-karriere/jobboerse/detail/berater-vertrieb-rind-aussendienst-futtermittel-m-w-d.html",
    "https://www.agriv.de/futter",
    "https://www.aircolor-dresden.de/pulverbeschichtung",
    "https://www.aiv-frankfurt.de/produkte/beleuchtung-und-elektrik",
    "https://www.ak-teck.de/produkte/kabelkonfektion-umspritzung",
    "https://www.ak-teck.de/unternehmen",
    "https://www.aku-kunststoff24.de/",
    "https://www.alpla.com/de/maerkte/milch-und-milchprodukte",
    "https://www.altendorfer-kunststofftechnik.de/",
    "https://www.alu-tecwvg.de/",
    "https://www.ams-metallbeschichtung.de/",
    "https://www.anpakgmbh.de/",
    "https://www.aot.de/lebensmittel/oele-fette.html",
    "https://www.apetito-catering.de/geschaeftsfelder/betriebs-gastronomie",
    "https://www.apetito.de/betriebe/beste-produkte-betriebe",
    "https://www.atco.de/zertifikate/",
    "https://www.atp-bartke-gmbh.de/",
    "https://www.atp-bartke-gmbh.de/pulverbeschichtung.html",
    "https://www.atr-landhandel.de/",
    "https://www.azelis.com/en/regions-and-locations/emea/germany",
    "https://www.baf-leubsdorf.de/",
    "https://www.baf-leubsdorf.de/leistung-und-service/pulverbeschichtung/",
    "https://www.bayern-fass.de/produkte/kunststoff/",
    "https://www.bayern-fass.de/unternehmen/",
    "https://www.bb-plastpack.de/",
    "https://www.benseler.de/de/",
    "https://www.benseler.de/de/unternehmen/standorte.php?procedure%5B%5D=332283332283",
    "https://www.benseler.de/de/verfahren/beschichtung/zinklamelle-schuettgut.php",
    "https://www.benteler.com/de/",
    "https://www.benteler.com/en/products-services/automotive-products/",
    "https://www.berckenbrinck.de/",
    "https://www.bergmann-automotive.de/",
    "https://www.bergmann-automotive.de/Impressum.html",
    "https://www.beschichtung.com/de/",
    "https://www.beschichtung.com/de/unternehmen/service/",
    "https://www.bia-group.com/unternehmen/index.php",
    "https://www.bigfood-gastro.de/",
    "https://www.binetti-group.com/en/",
    "https://www.bischof-klein.com/",
    "https://www.bix-lackierungen.de/",
    "https://www.blisterverpackung.de/blisterverpackungen/",
    "https://www.boehmler-drehteile.de/",
    "https://www.boewe-elektrik.de/automatisierungstechnik/",
    "https://www.boewe-elektrik.de/fileadmin/user_upload/01-11-11-IATF-16949-DE-EN-PL.pdf",
    "https://www.boewe-elektrik.de/profil-chronik/",
    "https://www.boge-rubber-plastics.com/sites/default/files/jobs/pdf/DED-24-28%20-%20MA%20IT%20Services%20%5BESA%5D.pdf",
    "https://www.bossert-gmbh.de/Impressum.html",
    "https://www.botan-food.de/",
    "https://www.brehm-praezision.de/images/pdf/IATF_16949_2027-06-23_de.pdf",
    "https://www.brenne.de/",
    "https://www.broekelmann-shop.de/",
    "https://www.broelio.de/wp-content/uploads/2025/03/IFS-Certificate-valid-until-29.04.2026.pdf",
    "https://www.broelio.de/zertifikate/",
    "https://www.brose-sitech.com/en/Company/Our-Locations",
    "https://www.buerkle-federn.de/drahtbiegeteile.html",
    "https://www.buerkle-federn.de/unternehmen.html",
    "https://www.bunge.com/deutschland",
    "https://www.c-o-o-p.de/en/products/cable-assembly/wiring-harnesses/",
    "https://www.cadcabel.com/",
    "https://www.calis-biocatering.de/kontakt.html",
    "https://www.cargill.com/food-beverage/emea/edible-oils",
    "https://www.cargill.com/food-beverage/emea/edible-oils/vegetable-oils",
    "https://www.cargill.de/de/lebensmittel-und-getr%C3%A4nke",
    "https://www.cefeg.de/slider-home/cefeg-gmbh-praezision-aus-chemnitz/",
    "https://www.certina-packaging.com/",
    "https://www.chefsculinar.de/",
    "https://www.chefsculinar.de/hi-taste-trifft-technik-50694.htm",
    "https://www.chefsculinar.de/index.htm",
    "https://www.coating-point.com/",
    "https://www.color-tec.de/unternehmen/",
    "https://www.continental-automotive.com/de.html",
    "https://www.cook-company.de/home/",
    "https://www.coroflex-cable.com/de/",
    "https://www.coroplast-group.com/de/wewire/",
    "https://www.corpack.de/de",
    "https://www.creavac.de/de/beschichtungen/",
    "https://www.creavac.de/de/beschichtungen/reflexbeschichtung/",
    "https://www.creavac.de/de/unternehmen/",
    "https://www.creavac.de/wp-content/uploads/2018/10/20181009-LB-allgemein.pdf",
    "https://www.cremeroleo.de/",
    "https://www.cremeroleo.de/de/produkte.html",
    "https://www.csp-deutschland.de/unternehmen/",
    "https://www.cup-service.de/",
    "https://www.dahmen-umformtechnik.de/",
    "https://www.deli-carte.de/zertifizierungen/",
    "https://www.denecke-fd.de/",
    "https://www.dietz.eu/unternehmen/",
    "https://www.dimexfood.de/",
    "https://www.diro-kunststoffe.de/",
    "https://www.dr-oette-maschinenbauteile.de/oberflaechentechnik-metallveredelung.html",
    "https://www.draexlmaier.com/en/supplier-portal/procurement",
    "https://www.draexlmaier.com/wer-wir-sind/zertifizierungen/europa",
    "https://www.dreistern-food.de/",
    "https://www.dreistern-food.de/unternehmen/marken/",
    "https://www.dresdnersilber.de/",
    "https://www.druckguss-schlicht.de/",
    "https://www.druko-metallguss.de/",
    "https://www.dw-zink.de/",
    "https://www.dynafond.de/",
    "https://www.e-m-u.net/ueberblick.html",
    "https://www.egv-group.de/solutions/high-convenience",
    "https://www.eib-mehlhorn.de/kabelbaeume-konfektionieren",
    "https://www.eib-mehlhorn.de/kabeltechnik",
    "https://www.einhaus-gmbh.de/leistungen/veredelung/",
    "https://www.elektronik-schmidt.eu/",
    "https://www.eltec-technology.com/en/products/wiring-harnesses/",
    "https://www.es-plastic.de/aktuellespresse/pressemitteilungen-detail/news/es-plastic-feiert-50-jaehriges-firmenjubilaeum-1/",
    "https://www.es-plastic.de/fileadmin/user_upload/2021_01_Ausschreibung_Lager_Teilzeit.pdf",
    "https://www.etm-rotterode.de/",
    "https://www.europa-catering.de/",
    "https://www.faerch.com/en",
    "https://www.faurecia.de/ueber-uns/ihre-ansprechpartner",
    "https://www.fazio-kabelkonfektion.de/kabelbaeume/",
    "https://www.febrotec.de/de-DE/unternehmen",
    "https://www.feg-jena.de/",
    "https://www.feindreh.de/zertifikate",
    "https://www.fg-haensch.de/produkte/kabelkonfektion/kabelkonfektion.html",
    "https://www.fiabuc.de/kontakt",
    "https://www.fiabuc.de/spektrum-1/automotive",
    "https://www.finoba-automotive.de/index.php?id=6&lang=de&site=Finoba%2FQUALIT%C3%84T%2F",
    "https://www.firner-trautwein.de/downloads/",
    "https://www.firstorientfood.de/",
    "https://www.forfarmersteamagrar.de/gefluegel",
    "https://www.forfarmersteamagrar.de/wissen-news/information_systemumstellung",
    "https://www.fps-catering.de/betriebsgastronomie/angebot/betriebsgastronomie",
    "https://www.freshfoodz.de/loesungen/restaurants",
    "https://www.frischdienst-union.de/logistikstandorte/",
    "https://www.frischkorn-gmbh.de/leistungen",
    "https://www.frosta-ag.com/unternehmen/marke-vertrieb/export-weltweit/",
    "https://www.frostafoodservice.de/produkte/gemuese/burger-patties/",
    "https://www.frostafoodservice.de/ueberblick/qualitaet-sicherheit/",
    "https://www.fsm-stamping.de/",
    "https://www.ftl-lorenz.de/lohnfertigung",
    "https://www.gadau.de/",
    "https://www.galvanikjaesche.de/unternehmen",
    "https://www.gaplast.de/",
    "https://www.gdft.de/",
    "https://www.geese-feinmechanik.de/",
    "https://www.geier-lacktechnik.de/industrie",
    "https://www.gfcs.com/content/dam/gfcs/as-about-gf-casting-solutions/as-sustainability/as-certificates/iatf-16949-werdohl-2024-en.pdf",
    "https://www.gfcs.com/de/market-segments/light-vehicles/e-engine-housing.html",
    "https://www.gizeh.com/de/",
    "https://www.gizeh.com/de/produkte/produktuebersicht/",
    "https://www.gourmetland-tk.de/",
    "https://www.greif.com/de/",
    "https://www.greiner-gpi.com/",
    "https://www.greiner-gpi.com/de/Greiner-Packaging/verpackungshersteller",
    "https://www.greiner-gpi.com/de/Markte/Food",
    "https://www.gustofaktur.de/news/ifs-food-version-6.1",
    "https://www.gutekunst-net.de/GKMainInformation-d.asp?lang=d",
    "https://www.gwp-ag.de/index.html",
    "https://www.gwp-ag.de/leistungen/serienfertigung/metallguss/index.html",
    "https://www.gwp-ag.de/unternehmen/maerkte/automotive/index.html",
    "https://www.habighorst.de/produkte/drahtbiegeteile/",
    "https://www.haertecenter.de/fileadmin/user_upload/HLH-IATF16949_Zertifikat_DEU_2024.pdf",
    "https://www.hagemann-dienste.de/futtermittelwerk/futtermittelhersteller/",
    "https://www.hagemann-dienste.de/groesste-futtermittelhersteller-deutschland/",
    "https://www.handelshof.de/sortiment/tiefkuehl-high-convenience",
    "https://www.handtmann.de/en/light-metal-casting/",
    "https://www.hardy-remagen.com/fileadmin/user_upload/Bilder/Auszeichnungen/EN_000231_CertificateIFS_Final.pdf",
    "https://www.heckler.de/",
    "https://www.heine-drehteile.de/",
    "https://www.heinrichs.de/",
    "https://www.heinrichs.de/en/quality/",
    "https://www.heinrichs.de/fileadmin/user_upload/downloads/qualitaet-und-umwelt/IATF_16949_Deutsch.pdf",
    "https://www.heinrichs.de/qualitaet/",
    "https://www.heismann.de/branchenloesungen/maschinen-und-anlagenbau",
    "https://www.hermann-drehteile.de/",
    "https://www.hessenkemper.com/produkte/aluminiumdruckguss/",
    "https://www.heuschkel-druckguss.de/wp-content/uploads/2015/08/IATF-16949_2016-de.pdf",
    "https://www.hillebrand-coating.com/",
    "https://www.hinterdobler.de/",
    "https://www.hirschvogel.com/news-media/newsletter/detail/ueberzeugt-mit-leichtigkeit-die-hirschvogel-aluminium-gmbh/",
    "https://www.hirt-praezision.de/",
    "https://www.hk-mueller.de/de/",
    "https://www.hk-mueller.de/de/branchen/lebensmittel/",
    "https://www.hl-futter.de/",
    "https://www.hn-metall.de/startseite.html",
    "https://www.hoco-muehle.com/",
    "https://www.hofmanns.de/auszeichnungen",
    "https://www.hofmanns.de/sozialverpflegung",
    "https://www.honsel.com/media/1272/iatf-16949-martinrea-honsel-germany-gmbh-deutsch.pdf",
    "https://www.hpl-pielhau.de/",
    "https://www.hunger-automotive.de/de/umformung",
    "https://www.hunstock-kabel.com/",
    "https://www.ilsen-gmbh.de/",
    "https://www.imo-gmbh.com/",
    "https://www.in-tec.de/de/kabelbaum-hersteller-automotive/",
    "https://www.in-tec.de/de/kabelkonfektion-deutschland",
    "https://www.intergast.de/",
    "https://www.jaun-neoform.de/",
    "https://www.jaun-neoform.de/verpackungen/feinkost-becher-schalen/",
    "https://www.jm-metall.de/",
    "https://www.jopp.com/de/",
    "https://www.jopp.com/de/loesungen/praezisionsdrehtechnik/",
    "https://www.jost-world.com/de/produkte/ktl-lohnbeschichtung.html",
    "https://www.juergenhake.de/en/",
    "https://www.jung-federn.de/",
    "https://www.kabelbenz.de/",
    "https://www.kaiserfood.de/uber-uns/",
    "https://www.kaley.de/",
    "https://www.kalmbach.de/de/home.html",
    "https://www.kama-futter.de/",
    "https://www.kesseboehmer.com/automotive/leistungen/montageteile",
    "https://www.kme.com/en/copperdivision/stamping",
    "https://www.kostbar-essen.de/jobs_category/koch/?export-pdf=1492",
    "https://www.kremaplast.de/",
    "https://www.kromberg-schubert.com/about-us/management",
    "https://www.kromberg-schubert.com/data/unternehmen/user_upload/downloads/E4.09.44.00_Supplier_Manual_Direct_Material_V11_Nov2025.pdf",
    "https://www.kromberg-schubert.com/data/unternehmen/user_upload/zertifikate/de-rhede-iatf-certificate-2025-en.pdf",
    "https://www.kromberg-schubert.com/the-wiring-systems-specialist/wiring-systems/quality",
    "https://www.kronenberg-eduard.com/produkte/automotive",
    "https://www.kroschu-cable.de/de/%C3%BCber-uns-284/ueber-uns/qualit%C3%A4t.html",
    "https://www.kroschu-cable.de/de/kabelwerk-deutschland-spezialkabel-hersteller-highend-kabel-lp.html",
    "https://www.ksmcastings.com/en/company/",
    "https://www.ksmcastings.com/qualitaet/",
    "https://www.ksmcastings.com/wp-content/uploads/2020/09/ZB-QSV-ZE-001_Teil_I_Allgemeine_Vereinbarung.pdf",
    "https://www.kummer-gmbh.de/",
    "https://www.kwdag.com/standorte/deutschland/wolfsburg.html",
    "https://www.lackierzentrum.eu/",
    "https://www.landolt-zerspanungstechnik.de/",
    "https://www.lang-metall.de/automotive.html",
    "https://www.laukoetter.com/",
    "https://www.leiber.com/de/produkte.html",
    "https://www.leiber.com/de/unternehmen.html",
    "https://www.leicht-mueller.de/de/stanzteile.html",
    "https://www.lemke.de/file/download/AMIfv95Ltbj4EFui3pxg2wnfs5W3SSIcK1FDfARCJUEUFOEmu6kgI8nb8Mgoaks94q7D9Ec_TSDS3FmsddVw8ghaX5hcjONnf4GsxLk90vhvbsM-9nIVKCKeY5PAqjLnuJAyBQDl1H6QYinK2tr5Knj7MkpzNEMpW-hK6vHL_EP13apZDBzKmoVmUjGvGjKaLocc1aQgvFVMWCF_TpcCEY2jO_E2upCGYAI2t9V-Qd3x-Qxz47K_OK4/IFS%20Food%20Georg%20Lemke%20GmbH%20%26%20Co.%20KG%2024%20de%20bis%2018.07.2026.pdf?download=1",
    "https://www.leoni.com/fileadmin/group/about-us/quality/leoni-quality-policy-acs.pdf",
    "https://www.lesjoforsab.com/de/produkt/drahtbiegeteile/",
    "https://www.likrawest.de/unternehmen/",
    "https://www.lnw.de/futtermittel",
    "https://www.loebke-federn.de/",
    "https://www.loebke-federn.de/produkte/drahtbiegeteile/",
    "https://www.lohr-solingen.de/",
    "https://www.lorenz-chieming.de/",
    "https://www.lov.de/",
    "https://www.mahle.com/en/products-and-services/passenger-cars/cooling/",
    "https://www.md-umformtechnik.de/branchen/automotive",
    "https://www.mecotec.com/",
    "https://www.mega-umform.de/ueber-uns/",
    "https://www.menueko.de/files/downloads/2024_IFS-F_Zertifikat_AGZ2428.pdf",
    "https://www.mesa-parts.com/de/branchenloesung/automobil/",
    "https://www.metalux.de/branchen/automobil/",
    "https://www.metro.de/unternehmen",
    "https://www.meyer-guenderoth.de/Verpackungen-93604.html",
    "https://www.mico-online.com/qualitaet-trifft-geschmack.html?cid=212&file=files%2Fmico%2Fproduktuebersicht%2F2025_MICO_Produkte_gesamt_01.25_neu_kompr.pdf",
    "https://www.mifuma.de/",
    "https://www.mifuma.de/faq",
    "https://www.modulteq.de/",
    "https://www.moser-technik.de/kabelbaeume/",
    "https://www.mouldtec.de/",
    "https://www.mpp-solutions.com/production",
    "https://www.mubea.com/de/achsfedersysteme",
    "https://www.mvg.group/firmenprofil-2/qulitaetsmanagement/",
    "https://www.mvg.group/jobs_category/produktion/",
    "https://www.mwg-gruppe.de/unternehmen/mwg-pulverbeschichtung-gmbh",
    "https://www.neeat.de/business-partners",
    "https://www.neupack.de/",
    "https://www.neusserformblech.de/",
    "https://www.ntn-at.de/geschaeftskunden/",
    "https://www.oberplast.de/",
    "https://www.oerlikon.com/balzers/de/de/maerkte/automobile-components/",
    "https://www.oesterle-formenbau.de/fertigung/",
    "https://www.oesterle-gmbh.com/",
    "https://www.oesterle-gmbh.com/druckguss/",
    "https://www.oetker-professional.de/",
    "https://www.oetker-professional.de/ueber-uns",
    "https://www.optipack.de/fileadmin/files/unternehmen/ISO-50001-DE.pdf",
    "https://www.opw-ingredients.com/de/",
    "https://www.pack-verde.com/de/home",
    "https://www.pahling-kabelkonfektion.de/",
    "https://www.peku.com/unternehmen/",
    "https://www.peotec.com/zertifizierungen.php",
    "https://www.plock-metallwerke.de/automotive/",
    "https://www.poeppelmann.com/de/famac/Verpackungen/Lebensmittelverpackungen/Kundenspezifische-Verpackungen.html",
    "https://www.poeppelmann.com/de/kapsto/Produkte/Thermoform-Trays.html",
    "https://www.poeppelmann.com/de/kapsto/Services/Performance.html",
    "https://www.poeppelmann.com/de/unternehmen/Wir/Unternehmensprofil.html",
    "https://www.pohl-verpackungen.de/",
    "https://www.pohl-verpackungen.de/startseite",
    "https://www.point-of-food.de/kontakt",
    "https://www.power-cast.com/media/files/zitzmann/pcz-iatf-en-2024.pdf",
    "https://www.power-cast.com/vobra-deutschland.html",
    "https://www.preh.com/fileadmin/user_upload/Downloads/Zertifizierungen/IATF-16949/Quality_management_-_certificate_IATF_16949-2016_March23.pdf",
    "https://www.premium-precision.com/leistungen/branchenkompetenz",
    "https://www.primamenue.de/",
    "https://www.primamenue.de/de/ueber-uns",
    "https://www.procolor-pulver.de/kontakt/",
    "https://www.protocast.de/",
    "https://www.provertha.de/wp-content/uploads/2024/07/Z_IATF-16949-K_de.pdf",
    "https://www.pulverlackierzentrum.de/",
    "https://www.pvtech.de/",
    "https://www.pw-sachsenlack-nfz.de/leistungen/industrielackierung/",
    "https://www.pw-sachsenlack-nfz.de/ueber-uns/",
    "https://www.raiffeisen-ems-vechte.de/ueber-uns/qualitaetsmanagement/",
    "https://www.raiffeisen-kraftfutterwerk.de/",
    "https://www.raiffeisen-kraftfutterwerk.de/portal/seiten/qualitaetsmanagement-900000136-10022.html",
    "https://www.rajapack.de/verpackungsnews/lebensmittelverpackungen",
    "https://www.rbayer.de/",
    "https://www.rettenberger.com/logistik/",
    "https://www.rimmler.com/",
    "https://www.rkw-kehl.de/",
    "https://www.rokatec.de/en/",
    "https://www.rose-medipack.de/de/",
    "https://www.rotover.de/",
    "https://www.rwg-grosslessen.raiffeisen.de/futtermittel",
    "https://www.saatenberg.com/",
    "https://www.salomon-foodworld.com/",
    "https://www.salomon-foodworld.com/de/fvz",
    "https://www.salvana.com/unternehmen/qualitaet/",
    "https://www.sander-jelinek.de/",
    "https://www.sandguss.de/",
    "https://www.schaeffler.com/en/divisions-products/",
    "https://www.schick-kunststoffverpackungen.de/",
    "https://www.schierer-galvanik.de/",
    "https://www.schkade-futter.de/",
    "https://www.schlote.com/schlote-gruppe/%C3%BCber-uns",
    "https://www.schlote.com/schlote-gruppe/schlote-gruppe/die-schlote-gesellschaften/schlote-gmbh-co-kg",
    "https://www.schmid-at.de/downloads.html?file=files%2Fdownloads%2FProspekte%2Fschmid-alutec_Prospekt.pdf",
    "https://www.schmid-folien.de/qualitaetsmanagement.html",
    "https://www.schneider-kunststoffverarbeitung.de/de/produkte",
    "https://www.schnitzelmacher.de/blank",
    "https://www.schoen-federn.de/",
    "https://www.schroeder-heidler.de/automobil",
    "https://www.schuele.de/de/unternehmen/julius-schuele-druckguss-gmbh",
    "https://www.schuele.de/fileadmin/old/user_upload/IATF_16949_2016_en.pdf",
    "https://www.schuetz-packaging.net/schuetz-germany-hq/en/innovations/schuetz-green-layer/",
    "https://www.schweitzer-lackierungen.de/",
    "https://www.schweizer-technologies.com/de/unternehmen/zertifizierung.html",
    "https://www.sebn.com/",
    "https://www.seeger-orbis.de/services/lohnhaerten",
    "https://www.sekona.de/",
    "https://www.selatec.de/",
    "https://www.servicebund.de/gemeinschaftsverpflegung.html",
    "https://www.sn-neuruppin.de/produkte/nutztiere",
    "https://www.spaleck.de/praezisionsteile/drehteile/",
    "https://www.special-coatings.com/de/lohnbeschichtung",
    "https://www.speedsignal.de/kabelkonfektion/",
    "https://www.spies-packaging.com/",
    "https://www.st-ji.com/de/startseite-trager-innovativer-losungen/standorte/saint-jean-industries-stuttgart-gmbh-de/",
    "https://www.stanzteile-paul.de/",
    "https://www.stanzteile.tech/",
    "https://www.stiehler-pm.de/",
    "https://www.stplettenberg.de/",
    "https://www.strubl.de/Standorte.html",
    "https://www.strubl.de/unternehmen.html",
    "https://www.subtil-group.com/de/technik/werkstoffe.html",
    "https://www.suedpack.com/de/food",
    "https://www.susa-sauer.de/de/praezisionsdrehteile",
    "https://www.susa-sauer.de/en/precision-turned-parts",
    "https://www.symanzik.de/",
    "https://www.symanzik.de/unternehmen/",
    "https://www.szae.de/de/pressteile-312.html",
    "https://www.tecpro-metall.de/",
    "https://www.tecpro-metall.de/qualitaet/",
    "https://www.th-electronic-mhl.de/fertigung/kabelkonfektionierung/kabelbaeume/",
    "https://www.thg-norderstedt.com/de/unternehmen",
    "https://www.thgeyer.com/de/ingredients/portfolio/lebensmittel/oele",
    "https://www.thoma-metallveredelung.de/",
    "https://www.thyssenkrupp-automotive-technology.com/en/company/profile",
    "https://www.transgourmet.de/sites/default/files/2024-09/formblatt_transgourmet_v2.pdf",
    "https://www.unger-kabelkonfektion.de/de/",
    "https://www.uniqfood.de/de/100-customised/",
    "https://www.voestalpine.com/automotivecomponents/en/content/download/23403/file/IATF%20169492016_de.pdf?inLanguage=ger-DE",
    "https://www.vogt-stanzteile.de/stanzteile-automobilindustrie/",
    "https://www.vortella.de/karriere",
    "https://www.voss.net/de/branchenloesungen/branche/automobil/",
    "https://www.vowalon.eu/",
    "https://www.wackermann-gmbh.de/",
    "https://www.wackermann-gmbh.de/aluminium-druckguss",
    "https://www.wagon-automotive.de/de/",
    "https://www.walter-rau.de/fuer-profis/foodservice/unser-sortiment/produktuebersicht/optima-frittierfett-halbfluessig-10-l",
    "https://www.weghorst-maschinenbau.de/",
    "https://www.weisspt.com/automobilbranche",
    "https://www.welp-group.com/de/",
    "https://www.werit.eu/de/kanister/",
    "https://www.werner-debatin-gmbh.de/industriebereich/fahrzeuglackierung/",
    "https://www.werner-schmid.de/stanzbiegeteile-aus-metall/",
    "https://www.whw.de/whw-hillebrand/",
    "https://www.wingert-foods.de/",
    "https://www.winter.de/",
    "https://www.wiotec.com/",
    "https://www.wmu.de/downloads/",
    "https://www.wmu.de/wp-content/uploads/sites/2/2024/04/IATF-16949-2016_de.pdf",
    "https://www.woelfle-gmbh.de/site/assets/files/6338/06_produktbroschuere_kabelkanaele.pdf",
    "https://www.wohlrab.de/en/job-coating",
    "https://www.wthalver.de/",
    "https://www.wuebken.de/futtermittel/",
    "https://www.zf.com/germany/de/home/home.html",
    "https://www.zf.com/master/media/migrated_data_certificates/Hannover_IATF16_31601655_en.pdf",
    "https://www.zf.com/products/en/cv/ind/home/cv.html",
    "https://www.zf.com/site/locations/ja/europe/germany_locations/germany.html",
    "https://zi-bza.de/",
    "https://zimmermann-federn.de/produkte/drahtbiegeteile/"
]


# ============================================================
# HILFSFUNKTIONEN
# ============================================================

def hole_domain(url):
    """Extrahiert die Domain aus einer URL (ohne www.)."""
    netloc = urlparse(url).netloc.lower()
    if netloc.startswith("www."):
        netloc = netloc[4:]
    return netloc


def hole_domain_rating(domain):
    """
    Fragt das Domain Rating bei Ahrefs ab.
    Rueckgabe: (wert, status)
    """
    headers = {
        "Accept": "application/json",
        "Authorization": f"Bearer {API_KEY}",
    }
    params = {
        "target": domain,
        "output": "json",
    }

    # Bis zu 3 Versuche, falls das Rate Limit zuschlaegt
    for versuch in range(1, 4):
        try:
            response = requests.get(API_URL, headers=headers, params=params, timeout=30)

            if response.status_code == 200:
                daten = response.json()
                return daten["domain_rating"]["domain_rating"], "OK"

            if response.status_code == 429:
                wartezeit = 30 * versuch
                print(f"   -> Rate Limit erreicht. Warte {wartezeit} Sekunden...")
                time.sleep(wartezeit)
                continue

            # 400 = ungueltiges Ziel, 401 = Key falsch, 403 = kein Zugriff
            return "", f"HTTP {response.status_code}"

        except Exception as e:
            print(f"   -> Netzwerkfehler: {e}")
            time.sleep(5)

    return "", "Fehler (Limit/Netzwerk)"


# ============================================================
# HAUPTFUNKTION
# ============================================================

def check_domain_rating():
    results = []
    cache = {}  # domain -> (wert, status)

    for index, url in enumerate(urls, 1):
        domain = hole_domain(url)
        print(f"[{index}/{len(urls)}] Pruefe: {domain}")

        # Bereits abgefragte Domain? Dann Wert aus dem Cache nehmen.
        if NUR_EINE_ABFRAGE_PRO_DOMAIN and domain in cache:
            wert, status = cache[domain]
            print(f"-> Aus Cache: DR {wert}")
        else:
            wert, status = hole_domain_rating(domain)
            cache[domain] = (wert, status)
            print(f"-> Domain Rating: {wert} ({status})")

            # Kurze Pause, damit die API nicht ueberrannt wird
            wait_time = random.uniform(1.0, 2.5)
            time.sleep(wait_time)

        results.append({
            "URL": url,
            "Domain": domain,
            "domain_rating": wert,
            "status": status,
        })

    # CSV-Export mit automatischer Erkennung (Anhaengen falls vorhanden)
    fieldnames = ["URL", "Domain", "domain_rating", "status"]
    file_exists = os.path.exists(CSV_DATEI)

    with open(CSV_DATEI, mode="a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)

        # Ueberschrift nur schreiben, wenn die Datei neu erstellt wird
        if not file_exists:
            writer.writeheader()

        writer.writerows(results)

    print(f"\nFertig! Ergebnisse wurden an '{CSV_DATEI}' angehaengt.")
    print("Hinweis: Bei Veroeffentlichung der Daten ist die Angabe")
    print("'Domain Rating by Ahrefs' (https://ahrefs.com/) verpflichtend.")


# Skript ausfuehren
if __name__ == "__main__":
    check_domain_rating()